# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointtype',
            name='points_count_partner',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
