# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_pointscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointtype',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
