# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-16 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_pointtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointscount',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
