# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_feesize_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactions',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
