# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='time_zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
