# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_place_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
