# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_place_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='age_group',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='music_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='opening_hours',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
