# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20160227_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='place_logo/%Y/%m/%d'),
        ),
    ]
