# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_place_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
