# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 13:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_checkin_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 14, 23, 59, 59)),
        ),
    ]
