# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 13:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_auto_20160318_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 23, 23, 59, 59)),
        ),
    ]
