# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 16:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_auto_20160330_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 31, 23, 59, 59)),
        ),
    ]
