# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 07:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_auto_20160331_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 3, 23, 59, 59)),
        ),
    ]
