# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 11:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0019_auto_20160403_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='last_push_expired',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 3, 11, 54, 57, 671927, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
