# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 05:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0020_place_last_push_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 7, 23, 59, 59)),
        ),
    ]
