# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 10:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0022_auto_20160408_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('id',), 'verbose_name': 'Venue', 'verbose_name_plural': 'Venues List'},
        ),
        migrations.AlterField(
            model_name='checkin',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 23, 59, 59)),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='city.City'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.FileField(null=True, upload_to='place/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='logo',
            field=models.FileField(null=True, upload_to='place_logo/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
