# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0025_auto_20160413_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='expired',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
