# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_devtoken_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(default=1, null=True)),
            ],
        ),
    ]
