# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_report_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='city',
        ),
    ]
