# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 07:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_remove_report_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='expired',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 3, 7, 44, 40, 39504, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
