# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_report_expired'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
            ],
            options={
                'verbose_name': 'Image/Video',
                'proxy': True,
                'verbose_name_plural': 'Added Images/Videos',
            },
            bases=('report.report',),
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('id',), 'verbose_name': 'Report', 'verbose_name_plural': 'Added Reports'},
        ),
        migrations.AlterField(
            model_name='report',
            name='bar_filling',
            field=models.IntegerField(blank=True, choices=[(0, 'A'), (1, 'B')], null=True),
        ),
    ]
