# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20160412_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='bar_filling',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
