# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='is_pushed',
            field=models.BooleanField(default=False),
        ),
    ]
