# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_follower_following_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='following',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
