# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_reportimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportimage',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
