# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20160223_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportimage',
            name='image',
            field=models.FileField(upload_to=b'report/%Y/%m/%d'),
        ),
    ]
