# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20160225_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportimage',
            name='thumb_video',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
