# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_reportimage_thumb_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportimage',
            name='thumb_video',
        ),
        migrations.AddField(
            model_name='reportimage',
            name='thumbnail',
            field=models.FileField(null=True, upload_to=b'report/video_thumb/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='reportimage',
            name='video',
            field=models.FileField(null=True, upload_to=b'report/video/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='image',
            field=models.FileField(null=True, upload_to=b'report/%Y/%m/%d'),
        ),
    ]
