# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20160408_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportimage',
            name='thumbnail',
            field=models.FileField(null=True, upload_to=b'thumbs/report/video/%Y/%m/%d'),
        ),
    ]
