# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0002_auto_20160407_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
